### ISSUE TITLE
Pull Requests not counted towards Hacktoberfest2020

### ISSUE THREAD

**Issue by TheRealDarkCoder** [omnone/pyRanoid#10]
Hello, this is an interesting and potential repository and I'd like to comet quite a few PRs to it,

However PRs are not counted towards the ongoing Hacktoberfest and it's not under the "Hacktoberfest" Topic. Adding the topic would not only make the repository more reachable to a wider audience but also provide some open source beginners to contribute to their first github repos. 

Please consider adding the topic. Learn more at [https://hacktoberfest.digitalocean.com/details#maintainers](https://hacktoberfest.digitalocean.com/details#maintainers)

**Comment by omnone** [comment]
Are you still experiencing this issue? It seems odd because all the issues are under the "Hacktoberfest" label.

**Comment by omnone** [comment]
I hadn't seen their update I will add it thanks !

**Comment by TheRealDarkCoder** [comment]
Thanks!
