### ISSUE TITLE
Fix radio buttons position

### ISSUE THREAD

**Issue by omnone** [omnone/pyRanoid#12]
Fix the radio buttons (marked as "decode" and "encode") position in order to be aligned with the text area below and the inputs above.

**Comment by gourav-j** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by ghanender-chauhan** [comment]
i want to work on it...please assign me this work

**Comment by omnone** [comment]
@ghanender-chauhan It's already assigned to @gourav-j  , you can work in some other issue .

**Comment by gourav-j** [comment]
@omnone I have raised a PR. Please check and merge.
