### ISSUE TITLE
Create documention

### ISSUE THREAD

**Issue by omnone** [omnone/pyRanoid#2]
Documentation for the project must be added such as usage , comments etc.

**Comment by tdserapio** [comment]
May I be assigned this task?

**Comment by Nithin005** [comment]
can i do it?

**Comment by TheRealDarkCoder** [comment]
Check Pull Request #6 
If we need to add/edit something, please comment.

**Comment by rakshit-puri** [comment]
I made some changes in the size and shape of the screenshot. #15
